editor: source

execute:
  cache: false
  freeze: false

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/_post-render.R"

title: "Agent-Based Modeling Study Group: 2024 Balance"
author: "Daniel Vartanian"
keyword: >
  Study Group. Agent-Based Models. Complexity Science. NetLogo.
institute: "University of São Paulo"
date: 2025-02-19
date-format: "YYYY-MM-DD"

website:
  favicon: images/sustentarea-icon.png
  site-url: https://danielvartan.github.io/abm-study-group-pres/
  repo-url: https://github.com/danielvartan/abm-study-group-pres/
  issue-url: https://github.com/danielvartan/abm-study-group-pres/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: "Agent-Based Model Study Group"
  repo-branch: main

format:
  revealjs:
    open-graph: true
    locale: en
    lang: en
    code-link: true
    code-fold: true
    link-external-newwindow: true
    tbl-cap-location: top
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    preview-links: false
    controls: true
    controls-layout: bottom-right
    chalkboard: true
    auto-stretch: true
    fig-align: center
    theme: [default, brand, scss/styles.scss]
    pdf-max-pages-per-slide: 1
    template-partials:
      - html/title-slide.html
    menu:
      titleSelector: [h1 h2]
      useTextContentForMissingTitles: false
      hideMissingTitles: false

google-scholar: false
bibliography: references.bib
